name: talk_to_task
description: "A voice-centric AI assistant for Grab drivers."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  flutter_tts: ^4.2.2
  google_maps_flutter: 2.10.1
  flutter_dotenv: ^5.1.0
  draggable_fab: ^0.1.4
  google_generative_ai: ^0.2.2
  just_audio: ^0.9.46
  http: ^1.3.0
  file_picker: ^6.1.1   # For picking audio file
  record: ^6.0.0
  path_provider: ^2.1.1  # Optional: for saving to temp directory
  path: ^1.9.0           # To handle file paths
  location: ^5.0.3
  geocoding: ^2.1.1
  battery_plus: ^6.2.1
  connectivity_plus: ^5.0.0
  intl: ^0.18.0
  weather: ^3.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/sounds/
    - .env


